### ISSUE TITLE
Issue running the app

### ISSUE THREAD

**Issue by Affanabbbas** [ajeetsk/openai-elasticsearch-rag#1]
![ES](https://github.com/user-attachments/assets/74832fd2-4b70-4bcb-91fb-0431897696c4)

I installed all the depedencies, installed ES and gave API key and other ES credentials in the .env environment file but I couldnt run the app (python run.py) by opening the above tow links as they show no connectivity.
what can be the possible soultion. please reply ASAP. 

Thanks

**Comment by ajeetsk** [comment]
I don't see any error here. Did you try `curl -X GET "localhost:8081"` - did it return 'Hello' ?

**Comment by Affanabbbas** [comment]
thanks for your prompt response.
the issue is when the cell is running, i cant run any other cell until it has been stopped. So i was unable to do it in google colab.
but I tried curl command in terminal but it did not work for me.

**Comment by Affanabbbas** [comment]
another question is, I have a huge data of books which I will be accessing though API.
is this code suitable to access huge data of books to asker queries from it?

**Comment by Affanabbbas** [comment]
I am waiting for your kind reply Ajeetsk.

**Comment by ajeetsk** [comment]
Can you try running the code on your laptop/ device first? Most of the users get it up and running without much trouble.

Regarding books - yes, you can. Just be cognisant about the size of chunk you are indexing. Refer code in app/routes/index_route.py and make suitable changes and try.

**Comment by Affanabbbas** [comment]
Thanks for your response.
After running "python run.py" on Pycharm, I got a reply, hello from RAG application.
Does that mean its working fine?

**Comment by ajeetsk** [comment]
Yes. You are all set. You may try other curls as well.

Go through the code to develop an understanding and make changes if needed.

Good luck!

**Comment by Affanabbbas** [comment]
Thank you Ajeetsk.

**Comment by Affanabbbas** [comment]
the 2nd curl is giving this error:
C:\Users\DELL>curl --location --request PUT "http://localhost:9200/first-index"
curl: (52) Empty reply from server

**Comment by ajeetsk** [comment]
Is ES running on your local machine? And have you configured the index as
per the read me?

**Comment by Affanabbbas** [comment]
I didn't get what you are saying. I'll really appreciate if you make it clear with a screenshot of what you are talking about.
The ES is running but i didn't get "the index as
per the read me"

**Comment by ajeetsk** [comment]
Follow read me document step by step, and it should work.
